components {
  id: "bases"
  component: "/cSCRIPTS/structures/bases.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"red_base\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/cRESOURCES/structures/structures.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "red_base_collider"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"env\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -11.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 225.0\n"
  "  data: 225.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "red_base_hitbox"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"red_base_hitbox\"\n"
  "mask: \"blue_attack\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -11.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 225.0\n"
  "  data: 225.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
