components {
  id: "minions"
  component: "/cSCRIPTS/minions.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"minion\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/cRESOURCES/minions/assets/minion.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "minion"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"minion\"\n"
  "mask: \"blue_attack\"\n"
  "mask: \"red_attack\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -24.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 13.0\n"
  "  data: 21.5\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
